from django.conf import settings
from django.db import models


class Insight(models.Model):
    """A stored, AI-generated (or rule-based fallback) insight. Insights are
    cached per-user/per-kind/per-day so repeated dashboard loads don't
    re-trigger an LLM call; ChatMessage history is separate.
    """
    class Kind(models.TextChoices):
        DAILY_SUMMARY = "daily_summary", "Daily Summary"
        WEEKLY_SUMMARY = "weekly_summary", "Weekly Summary"
        MONTHLY_SUMMARY = "monthly_summary", "Monthly Summary"
        RECOMMENDATION = "recommendation", "Recommendation"
        GOAL_FORECAST = "goal_forecast", "Goal Forecast"
        PRODUCTIVITY_TIP = "productivity_tip", "Productivity Tip"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="insights")
    kind = models.CharField(max_length=30, choices=Kind.choices)
    title = models.CharField(max_length=200)
    body = models.TextField()
    source = models.CharField(
        max_length=20, default="rule_based",
        help_text="'gemini' if generated by the LLM, 'rule_based' if generated by the fallback engine.",
    )
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.kind}] {self.title}"


class ChatMessage(models.Model):
    class Role(models.TextChoices):
        USER = "user", "User"
        ASSISTANT = "assistant", "Assistant"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="chat_messages")
    role = models.CharField(max_length=10, choices=Role.choices)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.role}: {self.content[:50]}"
